/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CarCategory = IDL.Variant({
  'suv' : IDL.Null,
  'sedan' : IDL.Null,
  'luxury' : IDL.Null,
  'hatchback' : IDL.Null,
});
export const CarModel = IDL.Variant({
  'xl6' : IDL.Null,
  'hyundaiXcent' : IDL.Null,
  'alto' : IDL.Null,
  'bmw5Series' : IDL.Null,
  'marutiCiaz' : IDL.Null,
  'innovaCrysta' : IDL.Null,
  'swiftDzire' : IDL.Null,
  'kiaCarens' : IDL.Null,
  'ertiga' : IDL.Null,
  'audiA6' : IDL.Null,
  'scorpio' : IDL.Null,
  'mercedesEClass' : IDL.Null,
  'swift' : IDL.Null,
  'tavera' : IDL.Null,
  'innova' : IDL.Null,
  'wagonR' : IDL.Null,
  'hondaAmaze' : IDL.Null,
});
export const Time = IDL.Int;
export const Booking = IDL.Record({
  'carModel' : CarModel,
  'carCategory' : CarCategory,
  'name' : IDL.Text,
  'seats' : IDL.Nat,
  'stops' : IDL.Vec(IDL.Text),
  'timestamp' : Time,
  'phone' : IDL.Text,
  'price' : IDL.Nat,
  'luggage' : IDL.Record({ 'count' : IDL.Nat, 'details' : IDL.Text }),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBooking' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        CarCategory,
        CarModel,
        IDL.Nat,
        IDL.Vec(IDL.Text),
        IDL.Record({ 'count' : IDL.Nat, 'details' : IDL.Text }),
        IDL.Nat,
      ],
      [IDL.Text],
      [],
    ),
  'createBookingWithStops' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        CarCategory,
        CarModel,
        IDL.Nat,
        IDL.Vec(IDL.Text),
        IDL.Record({ 'count' : IDL.Nat, 'details' : IDL.Text }),
        IDL.Nat,
      ],
      [IDL.Text],
      [],
    ),
  'findBookingByPhone' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(IDL.Tuple(IDL.Text, Booking))],
      ['query'],
    ),
  'getAllBookingsWithIdsSorted' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, Booking))],
      ['query'],
    ),
  'getBookingById' : IDL.Func([IDL.Text], [IDL.Opt(Booking)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCurrentPrincipalText' : IDL.Func([], [IDL.Text], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'hasAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'initializeAdmin' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitStops' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CarCategory = IDL.Variant({
    'suv' : IDL.Null,
    'sedan' : IDL.Null,
    'luxury' : IDL.Null,
    'hatchback' : IDL.Null,
  });
  const CarModel = IDL.Variant({
    'xl6' : IDL.Null,
    'hyundaiXcent' : IDL.Null,
    'alto' : IDL.Null,
    'bmw5Series' : IDL.Null,
    'marutiCiaz' : IDL.Null,
    'innovaCrysta' : IDL.Null,
    'swiftDzire' : IDL.Null,
    'kiaCarens' : IDL.Null,
    'ertiga' : IDL.Null,
    'audiA6' : IDL.Null,
    'scorpio' : IDL.Null,
    'mercedesEClass' : IDL.Null,
    'swift' : IDL.Null,
    'tavera' : IDL.Null,
    'innova' : IDL.Null,
    'wagonR' : IDL.Null,
    'hondaAmaze' : IDL.Null,
  });
  const Time = IDL.Int;
  const Booking = IDL.Record({
    'carModel' : CarModel,
    'carCategory' : CarCategory,
    'name' : IDL.Text,
    'seats' : IDL.Nat,
    'stops' : IDL.Vec(IDL.Text),
    'timestamp' : Time,
    'phone' : IDL.Text,
    'price' : IDL.Nat,
    'luggage' : IDL.Record({ 'count' : IDL.Nat, 'details' : IDL.Text }),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'phone' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBooking' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          CarCategory,
          CarModel,
          IDL.Nat,
          IDL.Vec(IDL.Text),
          IDL.Record({ 'count' : IDL.Nat, 'details' : IDL.Text }),
          IDL.Nat,
        ],
        [IDL.Text],
        [],
      ),
    'createBookingWithStops' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          CarCategory,
          CarModel,
          IDL.Nat,
          IDL.Vec(IDL.Text),
          IDL.Record({ 'count' : IDL.Nat, 'details' : IDL.Text }),
          IDL.Nat,
        ],
        [IDL.Text],
        [],
      ),
    'findBookingByPhone' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Tuple(IDL.Text, Booking))],
        ['query'],
      ),
    'getAllBookingsWithIdsSorted' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, Booking))],
        ['query'],
      ),
    'getBookingById' : IDL.Func([IDL.Text], [IDL.Opt(Booking)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCurrentPrincipalText' : IDL.Func([], [IDL.Text], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'hasAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'initializeAdmin' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitStops' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };