/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'carModel' : CarModel,
  'carCategory' : CarCategory,
  'name' : string,
  'seats' : bigint,
  'stops' : Array<string>,
  'timestamp' : Time,
  'phone' : string,
  'price' : bigint,
  'luggage' : { 'count' : bigint, 'details' : string },
}
export type CarCategory = { 'suv' : null } |
  { 'sedan' : null } |
  { 'luxury' : null } |
  { 'hatchback' : null };
export type CarModel = { 'hyundaiXcent' : null } |
  { 'alto' : null } |
  { 'bmw5Series' : null } |
  { 'marutiCiaz' : null } |
  { 'innovaCrysta' : null } |
  { 'swiftDzire' : null } |
  { 'ertiga' : null } |
  { 'audiA6' : null } |
  { 'scorpio' : null } |
  { 'mercedesEClass' : null } |
  { 'swift' : null } |
  { 'wagonR' : null } |
  { 'hondaAmaze' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string, 'phone' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBooking' : ActorMethod<
    [
      string,
      string,
      CarCategory,
      CarModel,
      bigint,
      Array<string>,
      { 'count' : bigint, 'details' : string },
      bigint,
    ],
    string
  >,
  'createBookingWithStops' : ActorMethod<
    [
      string,
      string,
      CarCategory,
      CarModel,
      bigint,
      Array<string>,
      { 'count' : bigint, 'details' : string },
      bigint,
    ],
    string
  >,
  'findBookingByPhone' : ActorMethod<[string], [] | [[string, Booking]]>,
  'getAllBookingsWithIdsSorted' : ActorMethod<[], Array<[string, Booking]>>,
  'getBookingById' : ActorMethod<[string], [] | [Booking]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCurrentPrincipalText' : ActorMethod<[], string>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'hasAdmin' : ActorMethod<[], boolean>,
  'initializeAdmin' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitStops' : ActorMethod<[string, Array<string>], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];